### ISSUE TITLE
Error when handling entity damage (event)

### ISSUE THREAD

**Issue by PineappleTurnovers** [dsdd/EnchantmentsPlusMinus#22]
Getting this error when dealing damage to entities. My server is 1.16.4 for reference. I would say the fix is that you need to check if a entity is null or not, although haven't properly looked at it myself.

`[13:43:39 ERROR]: Could not pass event EntityDamageByEntityEvent to EnchantmentsPlusMinus v1.4r-2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_16_R3.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
        at org.eps.pvppack.EnchantProcessor.onEntityDamageByEntity(EnchantProcessor.java:170) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor174.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-430]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:246) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1049) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:936) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:892) ~[patched_1.16.5.jar:git-Paper-430]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1081) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1830) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1165) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:844) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityArrow.a(EntityArrow.java:333) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:125) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityArrow.tick(EntityArrow.java:176) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.World.a(World.java:887) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1355) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-430]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-430]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by dsdd** [comment]
I've added a fix

**Comment by dsdd** [comment]
No reply after 7 days
