### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#29]
When anyone interacts with anything this happens

```
[17:11:01 ERROR]: Could not pass event InventoryClickEvent to EnchantmentsPlusMinus v1.6r-0
java.lang.NullPointerException: null
        at org.whyisthisnecessary.eps.visual.EnchantMetaWriter.getWrittenMeta(EnchantMetaWriter.java:132) ~[?:?]
        at org.whyisthisnecessary.eps.visual.EnchantMetaWriter.refreshItem(EnchantMetaWriter.java:275) ~[?:?]
        at org.whyisthisnecessary.eps.visual.EnchantMetaWriter.onInventoryClick(EnchantMetaWriter.java:284) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor224.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-465]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-465]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-465]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2540) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-465]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-465]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Steve-Tech** [comment]
I am also getting a few errors relating to EnchantMetaWriter (from PlayerInteractEvent and InventoryOpenEvent), but I don't think the source is up to date here since the line numbers don't match up and there is no refreshItem function, (so @dsdd are you able to push the most recent code please).

Thanks, Steve

**Comment by dsdd** [comment]
> I am also getting a few errors relating to EnchantMetaWriter (from PlayerInteractEvent and InventoryOpenEvent), but I don't think the source is up to date here since the line numbers don't match up and there is no refreshItem function, (so @dsdd are you able to push the most recent code please).
> 
> Thanks, Steve

Yeah I am, I haven't updated it in a long time

**Comment by dsdd** [comment]
Problem went over my head, didn't see the null check.
Just update to 1.6r-2
