### ISSUE TITLE
Error when death

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#32]
```
[23:36:10 ERROR]: Could not pass event PlayerDeathEvent to EnchantmentsPlusMinus v1.7r-2
java.lang.NullPointerException: null
        at org.eps.pvppack.EnchantProcessor.onPlayerKill(EnchantProcessor.java:251) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor172.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-469]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:852) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:676) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1268) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:759) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:845) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.Entity.entityBaseTick(Entity.java:449) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:266) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:406) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2449) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:154) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:515) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:176) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:390) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1382) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-469]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dsdd** [comment]
Fixed in latest version
