### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Dblxy** [dsdd/EnchantmentsPlusMinus#33]
```
[22:36:53 ERROR]: Could not pass event BlockBreakEvent to EnchantmentsPlusMinus v1.7r-3
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:748) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItemNaturally(CraftWorld.java:763) ~[patched_1.16.5.jar:git-Paper-469]
        at org.eps.pickaxepack.EnchantProcessor.onBlockBreak(EnchantProcessor.java:320) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor171.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-469]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-469]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:224) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1485) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001) ~[patched_1.16.5.jar:git-Paper-469]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-469]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by dsdd** [comment]
Sorry for the very late response, it should be fixed now

**Comment by Dblxy** [comment]
No problem and thank you!
