### ISSUE TITLE
get this error 1.19 paper MC

### ISSUE THREAD

**Issue by rackgaming** [dsdd/EnchantmentsPlusMinus#51]
Server version: Paper MC 1.19
`[02:54:28 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tokens' in plugin EnchantmentsPlusMinus v1.9r-13
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: File cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:299) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.vivi.eps.util.economy.TokenEconomy.getBalance(TokenEconomy.java:66) ~[Enchantments-.jar:?]
	at org.vivi.eps.command.TokensCommand.showTokens(TokensCommand.java:29) ~[Enchantments-.jar:?]
	at org.vivi.eps.command.TokensCommand.onCommand(TokensCommand.java:23) ~[Enchantments-.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more`

**Comment by dsdd** [comment]
i can't reproduce the error, can you provide info on the circumstances that caused this and also send me the usernamestore.yml file in plugins\EnchantmentsPlusMinus\data?

**Comment by rackgaming** [comment]
Sure, one second. another thing to note is I am using Prison and TokensEconomy(Which for some reason does not bring the tokens into the GUI as tokens either), even if I set it as Vault.

**Comment by rackgaming** [comment]
So while as OPerator or even as a normal person: I type /token exchange and no GUI pops open. and here is my usernamestore.yml TTVOGVampire: 3628453c-8c11-4600-b85f-6aa5fb1f7f3b

**Comment by rackgaming** [comment]
Update: ya it doesn't even recognize my username and if I do /enchantmentplusminus:paytokens username amount it says it cannot find me

**Comment by rackgaming** [comment]
Update: I used /eps changebal instead and that worked fine but that doesn't specify fixing the issue of getting tokens with other plugins or from vault idk.

**Comment by rackgaming** [comment]
Update: ya it seems to be conflicting with tokeneconomy

**Comment by dsdd** [comment]
> Sure, one second. another thing to note is I am using Prison and TokensEconomy(Which for some reason does not bring the tokens into the GUI as tokens either), even if I set it as Vault. which is here: https://www.spigotmc.org/resources/tokeneconomy-1-8-1-19-vault-support.101972/ also another thing to note is well you deleted the discord links on your pages so I have no other way of contact. also here is the prison plugins page: https://www.spigotmc.org/resources/prison.1223/

i think you already know this but the tokeneconomy that is built in eps is not the same as https://www.spigotmc.org/resources/tokeneconomy-1-8-1-19-vault-support.101972/. tokeneconomy refers to the built-in economy that my plugin loads in, in EnchantmentsPlusMinus/data

im still too not sure what is causing the error, but it appears(?) that somehow your player uuid is not being returned properly at
`public static UUID getUUID(String username)
	{
		String stringUUID = uuidDataStoreData.getString(username);
		if (stringUUID == null)
			return null;
		return UUID.fromString(stringUUID);
	}`
where uuidDataStoreData is usernamestore.yml, but since you have said that it is a conflict with tokeneconomy i do not know if the former situation is the case

**Comment by dsdd** [comment]
this is extremely strange behavior, try unistalling the jar and the folder and download from here https://github.com/dsdd/EnchantmentsPlusMinus/releases/tag/1.9r-13 ive tried this jar on a fresh offline server and it worked so if it doesnt work for you i dont think i can help you

**Comment by rackgaming** [comment]
is not a command in your plugin and that error happens which it shouldn't be giving that error but instead ignore that command

**Comment by rackgaming** [comment]
also it needs support for more of the vault placeholder %balance% is not the only vault command, there are things like vault_eco_ect

**Comment by rackgaming** [comment]
`[15:36:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tokens' in plugin EnchantmentsPlusMinus v1.9r-13
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: File cannot be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:299) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.vivi.eps.util.economy.TokenEconomy.getBalance(TokenEconomy.java:66) ~[Enchantments- (3).jar:?]
	at org.vivi.eps.command.TokensCommand.showTokens(TokensCommand.java:29) ~[Enchantments- (3).jar:?]
	at org.vivi.eps.command.TokensCommand.onCommand(TokensCommand.java:23) ~[Enchantments- (3).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more`

Same error but this time with /tokens bank

**Comment by TrollsterCooleg** [comment]
Should be a fix, just made the system for fetching UUIDS and returning of it less wierd and more readable.

**Comment by Geolykt** [comment]
The NPE is caused by the plugin attempting to fetch the balance of players that do not exist. Hence proper input sanitation should fix this issue

**Comment by rackgaming** [comment]
so is /tokens bank meant to open a GUI to put money in or something?

**Comment by rackgaming** [comment]
but are you talking about the balance of the bank or just in general? Because this has to do with the bank part(there is 0 tokens) in the bank but on regular /tokens I have tokens so likeee. how does one put the tokens in a bank lol

**Comment by rackgaming** [comment]
well I hope something can be fixed because some plugins are being conflicted with that plugin like TokensEconomy uses /tokens exchange and this plugin still tries to accept the input returning null with that error

**Comment by Geolykt** [comment]
Use spigot's `commands.yml` file to define aliases and bind the default "tokens" command to the proper plugin, then create another alias that binds to the other plugin's "tokens" command

**Comment by rackgaming** [comment]
Ya I use mycommand can definitely alias through that.

**Comment by rackgaming** [comment]
how do I use commands.yml for that sorry

**Comment by rackgaming** [comment]
am just gonna use your guys' token system for now. seems to work fine. he seems to be very inactive with support on his plugins but it was a great idea.

**Comment by rackgaming** [comment]
also, does mining affect just a mining server or does that work with regular mining as well

**Comment by dsdd** [comment]
> also, does mining affect just a mining server or does that work with regular mining as well

wutt it works with regular mining as well

**Comment by rackgaming** [comment]
so I have a bit of a problem, not that big of a deal BUT is there a way to set a certain item to not allow right clicking?

**Comment by dsdd** [comment]
fixed
