### ISSUE TITLE
[Another Bug] lol dont blame me

### ISSUE THREAD

**Issue by rackgaming** [dsdd/EnchantmentsPlusMinus#61]
`	java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.hasEnchant(org.bukkit.enchantments.Enchantment)" because "meta" is null
	at org.vivi.epsbuiltin.enchants.EnchantProcessor.onKill(EnchantProcessor.java:440) ~[Enchantments- (8).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1243.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:877) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1748) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1645) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1475) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1321) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2073) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2733) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2660) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1463) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:24:50 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:52 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:53 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:56 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:57 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:58 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:59 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:24:59 INFO]: --------------------------------------
[23:24:59 INFO]: Furniture async saving started
[23:24:59 INFO]: [FurnitureLib] Furniture save started
[23:25:01 INFO]: [FurnitureLib] 1 furniture has been saved to the database.
[23:25:01 INFO]: [FurnitureLib] 0 furniture has been updated in the database.
[23:25:01 INFO]: [FurnitureLib] 0 furniture has been removed from the database.
[23:25:01 INFO]: Furniture saving finish : 00:01.582
[23:25:01 INFO]: --------------------------------------
[23:25:01 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:25:02 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:25:03 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:25:04 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:25:04 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:25:05 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
[23:25:06 ERROR]: Could not pass event PlayerInteractEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: null
`

**Comment by rackgaming** [comment]
idk what to do bro, now even the bow is broken idk lol

**Comment by rackgaming** [comment]
`[01:23:02 ERROR]: Could not pass event PlayerRespawnEvent to EnchantmentsPlusMinus v1.9r-16
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null
	at org.vivi.epsbuiltin.enchants.EnchantProcessor.onPlayerRespawn(EnchantProcessor.java:611) ~[Enchantments- (7).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor465.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at com.earth2me.essentials.AsyncTeleport.lambda$respawnNow$6(AsyncTeleport.java:407) ~[EssentialsX-2.19.7.jar:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
	at com.earth2me.essentials.AsyncTeleport.respawnNow(AsyncTeleport.java:399) ~[EssentialsX-2.19.7.jar:?]
	at com.earth2me.essentials.AsyncTeleport.respawn(AsyncTeleport.java:384) ~[EssentialsX-2.19.7.jar:?]
	at com.earth2me.essentials.commands.Commandhome.lambda$run$2(Commandhome.java:79) ~[EssentialsX-2.19.7.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182) ~[?:?]
	at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:108) ~[EssentialsX-2.19.7.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170) ~[EssentialsX-2.19.7.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:814) ~[EssentialsX-2.19.7.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:717) ~[EssentialsX-2.19.7.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by dsdd** [comment]
> idk what to do bro, now even the bow is broken idk lol

i didnt write a default config file for the bow, you can just copy paste any other config and rename it as "flame.yml" and it will work again

**Comment by dsdd** [comment]
ok its done https://github.com/dsdd/EnchantmentsPlusMinus/releases/download/1.9r-16/Enchantments+-.jar

**Comment by rackgaming** [comment]
uh oh, now people can drag their item into the GUI and it deletes their item.
