### ISSUE TITLE
invalid plugin.yml, failed to download legacywrapper: 1.12

### ISSUE THREAD

**Issue by 1k3w** [dsdd/EnchantmentsPlusMinus#8]
i am on 1.12, and when i put in the plugin and restrat my server (not /rl) it gives me this
`[07:52:13 WARN]: org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
>
[07:52:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:76)
>
[07:52:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329)
>
[07:52:13 WARN]:        at org.whyisthisnecessary.eps.Main.onEnable(Main.java:142)
>
[07:52:13 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
>
[07:52:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
>
[07:52:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
>
[07:52:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
>
[07:52:13 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
>
[07:52:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
>
[07:52:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
>
[07:52:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
>
[07:52:13 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
>
[07:52:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
>
[07:52:13 WARN]:        at java.lang.Thread.run(Thread.java:748)
>
[07:52:13 WARN]: Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
>
[07:52:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158)
>
[07:52:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:74)
>
[07:52:13 WARN]:        ... 13 more
>
[07:52:13 WARN]: Caused by: java.util.zip.ZipException: zip file is empty
>
[07:52:13 WARN]:        at java.util.zip.ZipFile.open(Native Method)
>
[07:52:13 WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
>
[07:52:13 WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
>
[07:52:13 WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:166)
>
[07:52:13 WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:130)
>
[07:52:13 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:146)
>
[07:52:13 WARN]:        ... 14 more
>
[07:52:13 INFO]: Sorry, but it seems that there was an error downloading LegacyWrapper. To prevent data corruption, Enchantments+- will be forcefully disabled.If this mistake is unintentional, please report this to TreuGames for further investigation.
>
[07:52:13 INFO]: [EnchantmentsPlusMinus] Disabling EnchantmentsPlusMinus v1.0r-3
>
[07:52:13 INFO]: [PlaceholderAPI] Unregistered placeholder expansion: eps
>
[07:52:13 ERROR]: Error occurred while enabling EnchantmentsPlusMinus v1.0r-3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/whyisthisnecessary/legacywrapper/LegacyWrapper
        at org.whyisthisnecessary.eps.api.CustomEnchant.newEnchant(CustomEnchant.java:56) ~[?:?]
        at org.eps.pickaxepack.CustomEnchants.<clinit>(CustomEnchants.java:8) ~[?:?]
        at org.eps.pickaxepack.PackMain.onEnable(PackMain.java:12) ~[?:?]
        at org.eps.BuiltInPackParser.<init>(BuiltInPackParser.java:9) ~[?:?]
        at org.whyisthisnecessary.eps.Main.onEnable(Main.java:154) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: org.whyisthisnecessary.legacywrapper.LegacyWrapper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_275]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
        ... 16 more`

**Comment by dsdd** [comment]
Forgot to add files back, sorry about that

**Comment by dsdd** [comment]
Fixed this issue, just unistall LegacyWrapper from your plugins folder and update Enchantments+-.
